name: CI

on: [push]

jobs:
  build:

    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.0.100
    - name: dotnet --info
      run: dotnet --info
    - name: Build
      run: dotnet build
    - name: Run
      run: |
        echo $DOTNET_ROOT
        dotnet run dotnet-test.csproj --no-build
      env:
        DOTNET_ROOT: $DOTNET_ROOT/3.0.100/x64
